# Generated by Django 5.0.1 on 2024-02-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basics',
            fields=[
                ('nconst', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('primaryName', models.CharField(max_length=255)),
                ('birthYear', models.IntegerField()),
                ('deathYear', models.IntegerField(blank=True, null=True)),
                ('primaryProfession', models.CharField(max_length=255)),
                ('knownForTitles', models.CharField(max_length=255)),
                ('img_url_asset', models.URLField(blank=True, max_length=1024)),
            ],
        ),
    ]
