# Generated by Django 5.0.1 on 2024-02-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_remove_crews_id_remove_episode_id_remove_ratings_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='seasonNumber',
            new_name='numVotes',
        ),
    ]
