# Generated by Django 5.0.1 on 2024-02-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_alter_movies_endyear_alter_movies_img_url_asset_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basics',
            new_name='Names',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
