# Generated by Django 5.0.1 on 2024-02-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_alter_crews_tconst_alter_episode_episodenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleId', models.CharField(max_length=255)),
                ('ordering', models.SmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('language', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('types', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('attributes', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('isOriginalTitle', models.BooleanField(choices=[(0, 'False'), (1, 'True')], default=0)),
            ],
            options={
                'unique_together': {('titleId', 'ordering')},
            },
        ),
    ]
