# Generated by Django 5.0.1 on 2024-02-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_akas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.CharField(max_length=255)),
                ('ordering', models.SmallIntegerField()),
                ('nconst', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('job', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('characters', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('img_url_asset', models.URLField(blank=True, default='\\N', max_length=2000, null=True)),
            ],
            options={
                'unique_together': {('tconst', 'ordering')},
            },
        ),
    ]
