# Generated by Django 5.0.1 on 2024-02-05 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_basics_birthyear_alter_basics_img_url_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('tconst', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('titleType', models.CharField(choices=[('short', 'Short Movie'), ('movie', 'Long Movie'), ('tvEpisode', 'TV Episode')], max_length=20)),
                ('primaryTitle', models.CharField(max_length=255)),
                ('originalTitle', models.CharField(max_length=255)),
                ('isAdult', models.BooleanField(choices=[(0, 'False'), (1, 'True')], default=0)),
                ('startYear', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('endYear', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)])),
                ('runtimeMinutes', models.PositiveIntegerField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url_asset', models.URLField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
