# Generated by Django 5.0.1 on 2024-02-05 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_movies', to='myApp.basics')),
                ('tconst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.movies')),
                ('writers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_movies', to='myApp.basics')),
            ],
        ),
    ]
