# Generated by Django 5.0.1 on 2024-02-05 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_episode_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crews',
            name='id',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='id',
        ),
        migrations.AlterField(
            model_name='crews',
            name='tconst',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myApp.movies'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='tconst',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myApp.movies'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='tconst',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myApp.movies'),
        ),
    ]
