# Generated by Django 5.0.1 on 2024-02-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_rename_seasonnumber_ratings_numvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='endYear',
            field=models.CharField(blank=True, default='\\N', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='img_url_asset',
            field=models.URLField(blank=True, default='\\N', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='runtimeMinutes',
            field=models.PositiveIntegerField(blank=True, default='\\N', null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='startYear',
            field=models.CharField(max_length=255),
        ),
    ]
