# Generated by Django 5.0.1 on 2024-02-06 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_rename_basics_names_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crews',
            name='directors',
            field=models.ForeignKey(blank=True, default='\\N', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_movies', to='myApp.names'),
        ),
        migrations.AlterField(
            model_name='crews',
            name='writers',
            field=models.ForeignKey(blank=True, default='\\N', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_movies', to='myApp.names'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episodeNumber',
            field=models.PositiveIntegerField(blank=True, default='\\N', null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='seasonNumber',
            field=models.PositiveIntegerField(blank=True, default='\\N', null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.CharField(blank=True, default='\\N', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='titleType',
            field=models.CharField(choices=[('short', 'short'), ('movie', 'movie'), ('tvEpisode', 'tvEpisode')], max_length=20),
        ),
        migrations.AlterField(
            model_name='names',
            name='birthYear',
            field=models.CharField(blank=True, default='\\N', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='names',
            name='deathYear',
            field=models.CharField(blank=True, default='\\N', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='names',
            name='img_url_asset',
            field=models.URLField(blank=True, default='\\N', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='names',
            name='knownForTitles',
            field=models.CharField(blank=True, default='\\N', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='names',
            name='primaryProfession',
            field=models.CharField(blank=True, default='\\N', max_length=255, null=True),
        ),
    ]
