# Generated by Django 5.0.1 on 2024-02-06 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_alter_crews_directors_alter_crews_writers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='tconst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myApp.movies'),
        ),
    ]
