# Generated by Django 5.0.1 on 2024-02-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_alter_ratings_tconst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='tconst',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
