# Generated by Django 5.0.1 on 2024-02-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_alter_ratings_tconst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crews',
            name='tconst',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episodeNumber',
            field=models.CharField(blank=True, default='\\N', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='seasonNumber',
            field=models.CharField(blank=True, default='\\N', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='tconst',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
