# Generated by Django 5.0.1 on 2024-02-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_alter_crews_directors_alter_crews_writers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='averageRating',
            field=models.CharField(max_length=255),
        ),
    ]
