# Generated by Django 5.0.1 on 2024-02-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_alter_user_password_alter_user_username'),
        ('myApp', '0022_delete_customuser'),
    ]

    operations = [
    ]
