# Generated by Django 5.0.1 on 2024-02-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_disliked_liked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
