# Generated by Django 5.0.1 on 2024-02-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_merge_20240216_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('tconst', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('username', 'tconst')},
            },
        ),
    ]
